import { defineComponent } from "../Component";

/**
 * Marks an entity as never written to a saved `.ffscene` file - serializeScene
 * skips any entity carrying this tag. For editor-only entities whose whole
 * lifecycle is owned and regenerated by App itself (the transform gizmo's
 * handles, spawned/moved/despawned every frame from the current selection -
 * see App.render()), never something a user created that should survive a
 * save/load round trip.
 *
 * Deliberately separate from EditorOnly: a camera entity's icon is
 * EditorOnly (excluded from the final render) but must still persist - only
 * entities that are *also* Transient are excluded from saved files.
 *
 * A tag: there is nothing to store, mere presence is the information (see
 * PointLight's doc comment for the same pattern).
 */
export type TransientData = Record<string, never>;

export const Transient = defineComponent<TransientData>("Transient");
